config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'tables#show'
  get '/tables/show', to: 'tables#show'
  post '/tables/show', to: 'tables#show', as: 'tables'

  get '/tables/create', to: 'tables#show'

  get '/tables/new', to: 'tables#new', as: 'new_table_addition'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord
  def meow
    puts "meow"
  end
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  def show
    @task = params[:task]
    unless @task.nil?
      Todo.create(:task => @task)
    end


    @cat = Cat
    @user = User
    @todo = Todo
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fa17Hw4</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tables/new.html.erb
<%= form_tag tables_path do %>
  <%= label_tag(:task, "Cmon g add a task hurry hurry i dont have all day") %>
  <%= text_field_tag(:task, nil, placeholder: 'add a task') %>

  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

  <%= submit_tag("Create task") %>
<% end %>

app/views/tables/show.html.erb
<%= link_to('add a task to the list', new_table_addition_path) %>

<h1> tasks! </h1>
<ol>
  <% @todo.find_each do |todo| %>
    <li>
      <%= todo.task %>
    </li>
  <% end %>
</ol>

<h1> cats! </h1>
<% @cat.find_each do |cat| %>
  <p>
    Name: <%= cat.name %>
  </p>
<% end %>

<h1> users! </h1>
<% @user.find_each do |user| %>
  <p>
    Username: <%= user.username %> </br>
    Age: <%= user.age %> </br>
    Email: <%= user.email %> </br>
  </p>
<% end %>



<!-- fuck styling ur pages bare bones and ugly is the call -->